### ISSUE TITLE
sf failed slicing https://www.thingiverse.com/thing:2061197

### ISSUE THREAD

**Issue by dob71** [dob71/x2swn#7]
Raft procedure took 4 seconds.
Skirt layer count 1...
Skirt layer count 2...
Traceback (most recent call last):
  File "skeinforge/skeinforge_application/skeinforge_utilities/skeinforge_craft.py", line 227, in <module>
    main()
  File "skeinforge/skeinforge_application/skeinforge_utilities/skeinforge_craft.py", line 224, in main
    writeOutput(' '.join(sys.argv[1 :]), False)
  File "skeinforge/skeinforge_application/skeinforge_utilities/skeinforge_craft.py", line 135, in writeOutput
    return pluginModule.writeOutput(fileName, shouldAnalyze)
  File "C:\Program Files (x86)\x2sw_v1.2.0.1\skeinforge\skeinforge_application\skeinforge_plugins\craft_plugins\export.py", line 275, in writeOutput
    gcodeText = skeinforge_craft.getChainTextFromProcedures(fileName, procedures[: -1], gcodeText)
  File "C:\Program Files (x86)\x2sw_v1.2.0.1\skeinforge\skeinforge_application\skeinforge_utilities\skeinforge_craft.py", line 44, in getChainTextFromProcedures
    text = craftModule.getCraftedText(fileName, text)
  File "C:\Program Files (x86)\x2sw_v1.2.0.1\skeinforge\skeinforge_application\skeinforge_plugins\craft_plugins\skirt.py", line 85, in getCraftedText
    return getCraftedTextFromText(archive.getTextIfEmpty(fileName, text), repository)
  File "C:\Program Files (x86)\x2sw_v1.2.0.1\skeinforge\skeinforge_application\skeinforge_plugins\craft_plugins\skirt.py", line 95, in getCraftedTextFromText
    return SkirtSkein().getCraftedGcode(gcodeText, repository)
  File "C:\Program Files (x86)\x2sw_v1.2.0.1\skeinforge\skeinforge_application\skeinforge_plugins\craft_plugins\skirt.py", line 219, in getCraftedGcode
    self.parseLine(line)
  File "C:\Program Files (x86)\x2sw_v1.2.0.1\skeinforge\skeinforge_application\skeinforge_plugins\craft_plugins\skirt.py", line 293, in parseLine
    self.addSkirt(float(splitLine[1]))
  File "C:\Program Files (x86)\x2sw_v1.2.0.1\skeinforge\skeinforge_application\skeinforge_plugins\craft_plugins\skirt.py", line 180, in addSkirt
    closedLoop = outsetLoop + [outsetLoop[0]]
IndexError: list index out of range

**Comment by dob71** [comment]
Fixed in 1.3.0.1
